### ISSUE TITLE
custom-html.xsl

### ISSUE THREAD

**Issue by mitchkeller** [OpenDiscreteMath/ibl-combinatorics#121]
The custom-html.xsl here does not produce the same HTML that @oscarlevin  has posted. It looks like theres a separate repo used to host the book at the moment, and it has a different custom-html.xsl (produces problem type markers, suppresses solutions to exercises/supplementary chapter problems).  I'm going to let @oscarlevin make the PR to move that file in, since he knows better than I do what's going on with those files.

**Comment by oscarlevin** [comment]
I'll make a new version of the html tonight when I'm on my linux machine (with mbx tools).  The way I'm managing this is to work on the openmathbooks/bogart fork, update it from my fork of ibl-combinatorics, build the html there, then push the html to github.  Does this sound reasonable?  That way we don't have html in the root repository.

**Comment by mitchkeller** [comment]
That sounds eminently reasonable.

**Comment by oscarlevin** [comment]
I've updated the html version at bogart.openmathbooks.org
