### ISSUE TITLE
Contact Dartmouth

### ISSUE THREAD

**Issue by mitchkeller** [OpenDiscreteMath/ibl-combinatorics#131]
Someone needs to contact Dartmouth to tell them about this and ask them to link to it.

**Comment by mitchkeller** [comment]
If Dartmouth no longer wants to keep files up on their site, we'll have to discuss what we want to keep up and such.

**Comment by kentemorrison** [comment]
I contacted Dartmouth (in Sept. 2018). They updated their web pages with info about our version. They also maintain the final version of Bogart's and an archive of all the material he left. See
  https://math.dartmouth.edu/news-resources/electronic/kpbogart/
