### ISSUE TITLE
Chapter 4: a few typos

### ISSUE THREAD

**Issue by sphaso** [OpenDiscreteMath/ibl-combinatorics#136]
Hi!

**Problem 210c** states:
`How are \(\qchoose{m+n}{n}\) and \(\qchoose{m+n}{n}\) related?`
I believe you meant
`How are \(\qchoose{m+n}{n}\) and \(\qchoose{m+n}{m}\) related?`

**Problem 211a** states:

> In the left-hand side use the fact that%
> \begin{equation*}
> \sum_{i=1}^\infty a_ix^i = (\sum_{i=0}^\infty x^i) -a_0
> \end{equation*}

I believe an `a_i` got left out on the RHS:

` \sum_{i=1}^\infty a_ix^i = (\sum_{i=0}^\infty a_ix^i) -a_0`

In the next equation, I think the second equality should have an a_{i-1} instead of a_i. I'll copy it here for your convenience:

> \begin{equation*}
> \sum_{i=1}^\infty a_{i-1}x^i = x\sum_{i=1}^\infty a_ix^{i-1}
> =x\sum_{j=0}^\infty a_jx^j =x\sum_{i=0}^\infty a_ix^i
> \end{equation*}

**Footnote 5 in 4.3.2**
> Apparently Leanardo de Pisa

Misspelled: Le**o**nardo d**a** Pisa

**Comment by oscarlevin** [comment]
Thanks.  Will be fixed in imminent pull request.

**Comment by mitchkeller** [comment]
Closed by #137
