### ISSUE TITLE
Hints are not showing with label "Hint"

### ISSUE THREAD

**Issue by kentemorrison** [OpenDiscreteMath/ibl-combinatorics#20]
In the latex there is no "Hint" label being produced. See, for example, lines 11-14 in the source s1-3-apps.mbx, which is Activity 11.

**Comment by mitchkeller** [comment]
Hmmm. It's working properly for me. Can you try `git pull upstream update-bogart` to make sure that you've got the latest of everything and if it's still not working, please paste your `xsltproc` command into a comment on the bug report in case something is different there.

I'm attaching the PDF I get from `xsltproc` followed by `pdflatex`. If it's still not working for you, please attach your index.tex and index.pdf files here, too.
[index.pdf](https://github.com/OpenDiscreteMath/ibl-combinatorics/files/1033590/index.pdf)

**Comment by kentemorrison** [comment]
Problem solved. I didn't have latest matchbook xsl. I had a version with tasks but not hints.
