### ISSUE TITLE
Hints are missing from PTX

### ISSUE THREAD

**Issue by oscarlevin** [OpenDiscreteMath/ibl-combinatorics#26]
We need to manually add hints to activities/tasks.

**Comment by kentemorrison** [comment]
Do you mean the hints from combhints/pdfhintfiles?  I added those to the activities in 1.2. That's about 70 of the 225 total.

**Comment by oscarlevin** [comment]
Yes.  I saw that you added some but didn't realize how many you have done already.   This can remind us we have more to do.

**Comment by oscarlevin** [comment]
I'm going to break this up into chapters to assign (sign up) for them as I go.

**Comment by oscarlevin** [comment]
I believe we are done with this now, except for the odd hint missing from those sections that are missing all together.
