### ISSUE TITLE
Lots of unresolved xrefs

### ISSUE THREAD

**Issue by oscarlevin** [OpenDiscreteMath/ibl-combinatorics#28]
When I compile, there are still lots of unresolved xrefs.

**Comment by oscarlevin** [comment]
The pull request #59 fixes most of these, but some are due to discrepancies between the ptx and official pdf.

**Comment by mitchkeller** [comment]
When I've been editing, if it looks like a lot of work to track down the correct xml:id for something, I've been putting provisional="259" if the official PDF refers to Problem 259, and then we can go clean up the provisionals later on. Not necessarily suggesting that for others, but more noting it in case anyone else sees my provisionals and wonders what I'm up to.

**Comment by mitchkeller** [comment]
I'm going to dive in and fix all of these that are *not* in appendices. (I'm mainly just confused about what the status of the appendices is, so don't want to go mucking about with them at the moment.)

Step 1 will be to clean up the unresolved and duplicate situations. Then'll clean up my naughty provisional behavior.
