### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by mitchkeller** [OpenDiscreteMath/ibl-combinatorics#29]
Need to finish adding paths for images. Add comments here for images that are missing completely, and they can be created.

**Comment by mitchkeller** [comment]
The solution to problem 23 (in 1.2) seems to be the only image we definitely know is missing. More may be identified when making the PTX version match the PDF.

@oscarlevin Can you do a Tikz version of that image without too much extra effort? I'm having issues with Inkscape at the moment.

**Comment by oscarlevin** [comment]
I'll try to create the image soon.
