### ISSUE TITLE
Fix bad LaTeX

### ISSUE THREAD

**Issue by mitchkeller** [OpenDiscreteMath/ibl-combinatorics#31]
This is hopefully something that @davidfarmer can help us with. Off the top of my head, the things I know that need to be fixed are:

\choose needs to be replaced with \binom{}{}
\over needs to be replaced with \frac{}{}
`mrow` now typically has `& = &` where it should just have `& =`

**Comment by davidfarmer** [comment]
I can look at those three things.

How soon do you need this?

For the & = &, do you have a logical reason for converting to
  & =
instead of
  = &
?

**Comment by oscarlevin** [comment]
If @davidfarmer doesn't mind, I'd like to try my hand at this first.  I've been looking for an excuse to learn how to do this.

**Comment by mitchkeller** [comment]
I don't see this as urgent, I was more making the issue so that we remember to do it. I say go for it, @oscarlevin, and then perhaps @davidfarmer can help out if you run into a problem.

In terms of &= vs. =&, I guess I've always used &=. If there's a reason that =& is better, I have no objection.

**Comment by davidfarmer** [comment]
Okay with me!

Note that I am going to do this eventually anyway.  One of the
steps in my usual conversion is "fix_archaic_tex".  I am a bit
surprised that I had not encountered \over and \choose previously.
(Or at least I hadn't noticed that I needed to fix those.)

Let me know when you do it (but not how) and then I'll do it and
we can compare approaches.

**Comment by oscarlevin** [comment]
Okay, I've done it.  If anything, this was a good lesson in "just let David do it".  :)
