### ISSUE TITLE
6.2 has wrong PTX source

### ISSUE THREAD

**Issue by oscarlevin** [OpenDiscreteMath/ibl-combinatorics#50]
Apparently Bogart did an extensive rewrite of section 6.2.  There is at least one image missing and lots of differences in the problems and exposition.

**Comment by mitchkeller** [comment]
OK, I'll bite the the bullet on this one. 

Note to self: make sure to check the hints before you close this!

**Comment by oscarlevin** [comment]
@mitchkeller in pull request #59, I fixed the dihedral group notation in 6.2 already.  Hopefully it doesn't conflict with the work you are doing here.

Also, I noted at least one of the images has the old notation in it :(

**Comment by mitchkeller** [comment]
Minor merge conflict when rebasing, but only took me an extra minute or two.

I think that image many not have survived to the official PDF, but if it did, I've gotten really good at doing those things in TikZ already.
