### ISSUE TITLE
Problem numbering discrepancies

### ISSUE THREAD

**Issue by mitchkeller** [OpenDiscreteMath/ibl-combinatorics#61]
We're now to the point where I think we can go chapter by chapter and make sure that the problem numbers align. For instance, I noticed when finishing the major work on 6.2 that 6.1 now starts three problems ahead of the official PDF (in terms of counter: 251 vs 248) and ends two problem numbers ahead. Comment here with which chapters you've checked for alignment, and we'll close this once we know that all the chapters align in terms of first problem and last problem.

**Comment by mitchkeller** [comment]
I'll check over chapter 6.

**Comment by oscarlevin** [comment]
Problems 113 and 114 in the pdf are different than problem 113 in ptx.  This makes subsequent problems through chapter 2 off by 1.

**Comment by kentemorrison** [comment]
I thought I had fixed the problems in the 109 to 120 range of chapter 2. I will fix them.

**Comment by mitchkeller** [comment]
I did some looking at Chapter 5, and there seem to be a number of problem spots in there. I will look at that tomorrow morning.

**Comment by kentemorrison** [comment]
The problems in chapter 2 are okay now, except for the supplemental problems, which still need work.

**Comment by mitchkeller** [comment]
Looks like all that remains here is the appendices.

**Comment by kentemorrison** [comment]
Problem numbers match in Appendices A and B. Something is off in C. I will look at it now.

**Comment by oscarlevin** [comment]
@kentemorrison, I'm rewriting appendix C, and I'm already fixing them.

**Comment by kentemorrison** [comment]
@oscarlevin: I made a minor change in C-2 but I won't do any more in C. There's a lot to rewrite in the later sections of C with the introduction of combinatorial species. (I don't think I've ever seen them used in an undergrad text before.)

**Comment by oscarlevin** [comment]
Yes, I'm in the weeds on that right now.  It might need to wait until tomorrow.  I don't think your minor C-2 changes will mess anything up though, and I saw you caught something I missed.

**Comment by mitchkeller** [comment]
A good rebase should keep things nice and tidy, too. Or at least allow for a clean PR in case there are issues. Thanks for taking on the last widely divergent passage. I had enough fun with what I had to slog through in Chapters 5 and 6.

**Comment by kentemorrison** [comment]
I have checked all chapters and appendices, including supplemental problems. The problem numbers agree with the pdf. I trust that we all checked the wording of the problems in each section that we worked on, and so I'm closing this issue.
