### ISSUE TITLE
Supplementary problems

### ISSUE THREAD

**Issue by mitchkeller** [OpenDiscreteMath/ibl-combinatorics#64]
A lot of validation errors right now are the result of the structure of the supplementary problems. They need to be converted to exercises in order to support having solutions. I did Chapter 4 when I was working on it earlier in the summer. I'll do Chapter 5 when working on the rest of its issues tomorrow, since Chapter 5's supplementary problems are wrapped in activity instead of ol/li. The other ones can/should likely be done as a batch with a proper find/replace.

**Comment by kentemorrison** [comment]
I'm working on the supplementary problems in chapter 2. I don't think there is a file for the butane molecule (Figure 2.8) in problem 3.

**Comment by mitchkeller** [comment]
@kentemorrison There's another missing molecule diagram in Chapter 6. I'm going to make a new issue for missing figures so that we can start collecting them there.

**Comment by mitchkeller** [comment]
Chapter 5 is already in a PR #66, and I've just done Chapter 3. Will work on Chapter 1 and then Chapter 6. Leaving Chapter 2 alone, since @kentemorrison is working on it.

**Comment by mitchkeller** [comment]
Appendix C is the only appendix with supplementary problems.
