### ISSUE TITLE
initialdigraph2 and initialdigraph3

### ISSUE THREAD

**Issue by kentemorrison** [OpenDiscreteMath/ibl-combinatorics#74]
This is not urgent, just annoying. When I process the tex file the image files initialdigraph2 and initialdigraph3 cannot be found:

! LaTeX Error: File `images/initialdigraph2' not found.

I think it is because the Mac OS does not trust the content creator of these files and will not open them, although I am not sure. The creator is listed as cairo 1.15.2 (http://cairographics.org). The similar image file  initialdigraph works just fine. It's creator is TeX.

**Comment by oscarlevin** [comment]
That's strange.  I made those images in inkscape the other day since I could do so easily from initialdigraph.svg.  I'll try to convert both to tikz soon here.

**Comment by mitchkeller** [comment]
That's weird. I'm not running into the same problem here, but I may have different security settings than @kentemorrison does on his Mac.

**Comment by kentemorrison** [comment]
Oscar,

Don't convert them yet. Let me experiment some more. I just successfully got initialdigraph2 to display in another LaTeX document.

**Comment by oscarlevin** [comment]
Okay, I'll hold for now.

**Comment by kentemorrison** [comment]
Problem solved. I'm embarrassed to confess this, but I had forgotten that I made copy of images files for my output folder. Somehow I didn't copy initialdigraph2 and 3.
