### ISSUE TITLE
Index could use some love

### ISSUE THREAD

**Issue by oscarlevin** [OpenDiscreteMath/ibl-combinatorics#87]
The index does not match the pdf.  This is probably a low-level request, as our index is pretty good already, but it might be worth checking for any obvious errors.

**Comment by mitchkeller** [comment]
We should definitely aim to have our index be a superset of the original. I know I added a few idx tags along the way where I was surprised there weren't any, but I'm sure we also missed some things, especially in the passages where the official PDF and the source were so divergent.

**Comment by oscarlevin** [comment]
I'll work some on this, starting from the back of the alphabet, to meet @kentemorrison somewhere in the middle.

**Comment by kentemorrison** [comment]
Today I'm setting up my new Mac laptop, replacing my 7 year old one. I'm hoping to do all the file transfer from my backup disk, so that I can keep working on the index from my old computer. We'll see...

**Comment by kentemorrison** [comment]
@oscarlevin   I've finished H-O in the index but haven't pushed it. Where are you?

**Comment by oscarlevin** [comment]
@kentemorrison I'm just starting on Z.  I got pulled in to start of semester stuff this morning :(

**Comment by kentemorrison** [comment]
I will keep going, then, starting on P.

**Comment by oscarlevin** [comment]
I'm in the middle of S now.  First person to get to R wins!

**Comment by oscarlevin** [comment]
I'm working on R.

**Comment by oscarlevin** [comment]
Done with Q.  I'll push momentarily.

**Comment by kentemorrison** [comment]
Wow! You're fast. You win! I will push with edits through P.

**Comment by oscarlevin** [comment]
There wasn't much to change.
